apiVersion: v1
kind: PersistentVolume
metadata:
  name: dev-postgres-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/dev-postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-postgres-pvc
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi