apiVersion: v1
kind: PersistentVolume
metadata:
  name: prod-postgres-pv
  namespace: prod
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/prod-postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prod-postgres-pvc
  namespace: prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
